USE datakaryawan;

CREATE TABLE IF NOT EXISTS work_schedules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  active_shift ENUM('Pagi', 'Siang', 'Malam') NOT NULL DEFAULT 'Pagi',
  pagi_time TIME NOT NULL DEFAULT '08:00:00',
  siang_time TIME NOT NULL DEFAULT '13:30:00',
  malam_time TIME NOT NULL DEFAULT '21:00:00',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_work_schedules_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
